### ISSUE TITLE
SISTEMA - ALUNO - HOME

### ISSUE THREAD

**Issue by leocostaba** [InfoJrUFBA/escola-recriar#17]
Como aluno, eu gostaria de ter uma home page onde eu pudesse ver algumas atividades para hoje, e os meu horarios

**Comment by RafaelBarretto** [comment]
- [ ] Mostrar a data e o dia da semana
- [ ] Mostrar horários das disciplinas da semana com nome do professor
       * [ ] Importar algumas informações do planejamento (semana)
       * [ ] Importar informações do Calendário (semana)
