### ISSUE TITLE
SISTEMA - ALUNO - ATIVIDADES

### ISSUE THREAD

**Issue by leocostaba** [InfoJrUFBA/escola-recriar#19]

**Comment by neivison** [comment]
- [ ] Visualizar atividades
- [ ]  Possibilidade de downloads das apostilas

**Comment by leocostaba** [comment]
Eu gostei da liberdade criativa que você teve @neivison, porém temos que fazer algumas correções em relação ao moqups, são elas:

- Tamanho do nome do aluno, está enorme! trazendo um fluxo desproporcional.
- Botão OK, ficou muito pequeno. Devemos utilizar o seguinte:
`border: medium none;
padding: 5px 15px;
border-radius: 5px;`
